apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: "user13.azurecr.io/subscription:latest"
          ports:
            - containerPort: 8080
          env:
          - name: CLASS
            valueFrom:
              configMapKeyRef:
                name: subscription-config
                key: class
          volumeMounts:
          - mountPath: "/mnt/data"
            name: volume
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
